### PR TITLE
Cleaning some of the code

### PR DESCRIPTION
**Pull request by darltrash**
- Remove unnecessary abstraction
- Enable using the first argument as the cores path
- Removed `utils.lua` and `middleclass.lua`
- Changed `ls` with `find`
- Localized as most as I could

### CODE REVIEW

**Comment by sodomon2** [comment]
@darltrash ah

**Comment by darltrash** [comment]
@darltrash @Sodomon ahi va :)

**Comment by sodomon2** [comment]
@darltrash xd

**Comment by sodomon2** [comment]
@sodomon2 xd

**Comment by sodomon2** [comment]
Thanks!

**Pull request merged**
